flags: {}
extra-package-dbs: []
packages:
- '.'
resolver: lts-18.13
allow-newer: true
ghc-options:
  hashable: -fno-prof-auto
  unordered-containers: -fno-prof-auto
nix:
  enable: true
  shell-file: shell.nix
